<?php
$moduleId       = rand().time();
$module_seletor = "autosearch".$moduleId;
$helper         = $this->helper('Magento\Search\Helper\Data');
$searchHelper   = $this->helper('Lof\Autosearch\Helper\Data');
$blockId        = 'lof-search' . $moduleId;
?>
<div class="<?php echo $prefix; ?> lof-autosearch box search_box" id="<?php echo $blockId ?>">
    <form class="search-form" method="GET" id="form<?php echo $blockId ?>" action="<?php echo $this->getCatalogAdvancedSearchLink(); ?>">
        <?php if(!empty($categories)) { ?>
            <div id="<?php echo $module_seletor ?>" class="lof-search control fifty-percent">
                <input 
                type="text"
                name="<?php echo $helper->getQueryParamName() ?>"
                value="<?php echo $helper->getEscapedQueryText() ?>"
                placeholder="<?php echo __('Search Product'); ?>"
                class="search-bar"
                autocomplete="off"/>
                <input type="hidden" name="name" placeholder="<?php echo __('Search entire store here...'); ?>" value="<?php echo $helper->getEscapedQueryText() ?>" class="input-text" autocomplete="off"/>
            </div>
            <?php } ?>
            <div class="filter_type category-filter category-search fifty-percent">
                <select class="input-bar" name="cat">
                    <option value="<?php echo $this->getRootCategoryId(); ?>"><?php echo __("All Categories"); ?> </option>
                    <?php echo $categories; ?>
                </select>
                <i class="chevron-icon fa-solid fa-chevron-down"></i>
                <button class="search-custom-icon search-icon fa fa-search"></button>
            </div>     
        </form>
        <?php if(($trendingCollection = $block->getTerms()) && $trendingCollection->getSize()){ ?>
            <div id="search-tags" class="search-tags">
                <div class="title">
                    <span><?php echo __('Trending keywords:'); ?></span>
                </div>
                <div class="content">
                    <?php foreach ($trendingCollection as $_term): ?>
                    <a href="<?php echo $this->getCatalogAdvancedSearchLink(); ?>?name=<?php echo $block->escapeHtml($_term->getQueryText()) ?>" style="font-size:<?php echo $_term->getPopularity()/100*80+90 ?>%;">
                        <?php echo $block->escapeHtml($_term->getQueryText()) ?>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
        <?php } ?>
    </div>
